apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: team-backend
  labels:
    app: users-api
    team: backend
    component: api
    tier: backend
  annotations:
    description: "Service for users API backend"
    business-purpose: "Backend API for load balancing demo"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/api/health"
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: users-api
    team: backend
  sessionAffinity: None  # Important: No sticky sessions for load balancing demo