# Backend Auto-scaling and High Availability
# =============================================================================
# HORIZONTAL POD AUTOSCALER
# =============================================================================

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: users-api-hpa
  namespace: team-backend
  labels:
    app: users-api
    team: backend
    component: autoscaling
    tier: backend
  annotations:
    description: "Auto-scaling for users API"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-api
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15 # 60 in realtà ho messo 15 per demo veloce
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15 # 60
    scaleDown:
      stabilizationWindowSeconds: 30 # 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15 # 60

# =============================================================================
# POD DISRUPTION BUDGET
# =============================================================================

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: users-api-pdb
  namespace: team-backend
  labels:
    app: users-api
    team: backend
    component: availability
    tier: backend
  annotations:
    description: "Ensure backend API availability during maintenance"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: users-api
      team: backend