# Frontend Auto-scaling and High Availability
# =============================================================================
# HORIZONTAL POD AUTOSCALER
# =============================================================================

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: react-store-hpa
  namespace: team-frontend
  labels:
    app: react-store
    team: frontend
    component: autoscaling
    tier: frontend
  annotations:
    description: "Auto-scaling for React store demo"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-store
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60

# =============================================================================
# POD DISRUPTION BUDGET
# =============================================================================

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: react-store-pdb
  namespace: team-frontend
  labels:
    app: react-store
    team: frontend
    component: availability
    tier: frontend
  annotations:
    description: "Ensure frontend availability during node maintenance"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: react-store
      team: frontend