apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2025-06-19T10:13:04Z"
    labels:
      kubernetes.io/metadata.name: default
    name: default
    resourceVersion: "8"
    uid: c4fd3b53-5367-4ee0-9e53-32b00c148f75
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2025-06-19T10:13:04Z"
    labels:
      kubernetes.io/metadata.name: kube-node-lease
    name: kube-node-lease
    resourceVersion: "11"
    uid: b4e2cb71-8b7b-41c6-8385-aaf1c6fb6857
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2025-06-19T10:13:04Z"
    labels:
      kubernetes.io/metadata.name: kube-public
    name: kube-public
    resourceVersion: "7"
    uid: 66912ada-4c6e-4528-9bf2-31384e0db2f6
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2025-06-19T10:13:04Z"
    labels:
      kubernetes.io/metadata.name: kube-system
    name: kube-system
    resourceVersion: "4"
    uid: 263903a2-f911-4e05-82bd-45b7f6482203
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"local-path-storage"}}
    creationTimestamp: "2025-06-19T10:13:08Z"
    labels:
      kubernetes.io/metadata.name: local-path-storage
    name: local-path-storage
    resourceVersion: "294"
    uid: 9dce7535-88c4-4b14-843a-ba971dfc9424
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2025-06-19T10:17:12Z"
    labels:
      kubernetes.io/metadata.name: test-connectivity
    name: test-connectivity
    resourceVersion: "1145"
    uid: 155edb64-5194-4c0a-896c-a85d7c748964
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
kind: List
metadata:
  resourceVersion: ""
