# Multi-Tenant ServiceAccounts Configuration
# Created: Step 3 of multi-tenant implementation
# Purpose: Identity management for each team

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-frontend-sa
  namespace: team-frontend
  labels:
    team: frontend
    component: identity
    setup-step: "step-3"
  annotations:
    description: "ServiceAccount for frontend team workloads and RBAC"
    created-by: "multi-tenant-setup"
    kubernetes.io/managed-by: "platform-team"
# Auto-mount service account token for pod authentication
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-backend-sa
  namespace: team-backend
  labels:
    team: backend
    component: identity
    setup-step: "step-3"
  annotations:
    description: "ServiceAccount for backend team workloads and RBAC"
    created-by: "multi-tenant-setup"
    kubernetes.io/managed-by: "platform-team"
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-platform-sa
  namespace: team-platform
  labels:
    team: platform
    component: identity
    setup-step: "step-3"
  annotations:
    description: "ServiceAccount for platform team infrastructure operations"
    created-by: "multi-tenant-setup"
    kubernetes.io/managed-by: "platform-team"
    privilege-level: "cluster-admin"
automountServiceAccountToken: true