apiVersion: v1
kind: Pod
metadata:
  name: test-master
  namespace: test-connectivity
spec:
  nodeName: multi-tenant-control-plane
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker1
  namespace: test-connectivity
spec:
  nodeName: multi-tenant-worker
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker2
  namespace: test-connectivity
spec:
  nodeName: multi-tenant-worker2
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "3600"]