# Multi-Tenant Resource Quotas Configuration

# =============================================================================
# FRONTEND TEAM RESOURCE QUOTA
# =============================================================================

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-frontend-quota
  namespace: team-frontend
  labels:
    team: frontend
    component: governance
  annotations:
    description: "Resource limits and cost control for frontend team"
    monthly-budget: "$500"
    contact: "frontend-team@company.com"
spec:
  hard:
    # Compute Resources
    requests.cpu: "4"        
    requests.memory: 8Gi 
    limits.cpu: "8"          
    limits.memory: 16Gi   
    
    # Kubernetes Objects
    pods: "50"      
    services: "10"  
    secrets: "20"   
    configmaps: "20"
    
    # Storage
    requests.storage: 100Gi     
    persistentvolumeclaims: "10"
    
    # Networking
    services.nodeports: "2"     
    services.loadbalancers: "1" 

---
# LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: team-frontend-limits
  namespace: team-frontend
  labels:
    team: frontend
    component: governance
  annotations:
    description: "Default resource limits for frontend team pods"
spec:
  limits:
  
  - default:
      cpu: 200m              
      memory: 256Mi          
    defaultRequest:
      cpu: 100m              
      memory: 128Mi          
    max:
      cpu: "2"               
      memory: 4Gi            
    type: Container

# =============================================================================
# BACKEND TEAM RESOURCE QUOTA
# =============================================================================

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-backend-quota
  namespace: team-backend
  labels:
    team: backend
    component: governance
  annotations:
    description: "Resource limits and cost control for backend team"
    monthly-budget: "$800"
    contact: "backend-team@company.com"
spec:
  hard:
    # Compute Resources
    requests.cpu: "6"           
    requests.memory: 12Gi       
    limits.cpu: "12"            
    limits.memory: 24Gi         
    
    pods: "75"                  
    services: "15"              
    secrets: "30"               
    configmaps: "30"            
    
    # storage
    requests.storage: 200Gi     
    persistentvolumeclaims: "15"
    
    # Networking
    services.nodeports: "1"     
    services.loadbalancers: "0" 

---
# LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: team-backend-limits
  namespace: team-backend
  labels:
    team: backend
    component: governance
  annotations:
    description: "Default resource limits for backend team pods"
spec:
  limits:
  
  - default:
      cpu: 500m              
      memory: 512Mi          
    defaultRequest:
      cpu: 200m              
      memory: 256Mi          
    max:
      cpu: "4"               
      memory: 8Gi            
    type: Container

# =============================================================================
# PLATFORM TEAM RESOURCE QUOTA
# =============================================================================

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-platform-quota
  namespace: team-platform
  labels:
    team: platform
    component: governance
  annotations:
    description: "Resource limits for platform team infrastructure"
    monthly-budget: "$1200"
    contact: "platform-team@company.com"
spec:
  hard:
    # Compute Resources
    requests.cpu: "8"           
    requests.memory: 16Gi       
    limits.cpu: "16"            
    limits.memory: 32Gi         
    
    
    pods: "100"                 
    services: "25"              
    secrets: "50"               
    configmaps: "50"            
    
    # Storage
    requests.storage: 500Gi     
    persistentvolumeclaims: "25"
    
    # Networking
    services.nodeports: "10"    
    services.loadbalancers: "5" 

---
# LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: team-platform-limits
  namespace: team-platform
  labels:
    team: platform
    component: governance
  annotations:
    description: "Default resource limits for platform team infrastructure"
spec:
  limits:
  - default:
      cpu: "1"               
      memory: 1Gi            
    defaultRequest:
      cpu: 500m              
      memory: 512Mi          
    max:
      cpu: "8"               
      memory: 16Gi           
    type: Container