apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: users-api-metrics
  namespace: team-backend
  labels:
    app: users-api
    team: backend
    monitoring: enabled
    release: prometheus
spec:
  selector:
    matchLabels:
      app: users-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s