apiVersion: v1
kind: Service
metadata:
  name: react-store
  namespace: team-frontend
  labels:
    app: react-store
    team: frontend
    component: web-app
    tier: frontend
  annotations:
    description: "Service for React store demo application"
    business-purpose: "Load balancing demonstration for frontend team"
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: react-store
    team: frontend
  sessionAffinity: None