# Multi-Tenant Namespaces Configuration

---
apiVersion: v1
kind: Namespace
metadata:
  name: team-frontend
  labels:
    # Team
    team: frontend
    environment: development
    
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    
    # labels
    cost-center: engineering
    compliance: standard
    
  annotations:
    description: "Frontend team"

---
apiVersion: v1
kind: Namespace
metadata:
  name: team-backend
  labels:
    # Team
    team: backend
    environment: development
    
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    
    # labels
    cost-center: engineering
    compliance: standard
    
  annotations:
    description: "Backend team"

---
apiVersion: v1
kind: Namespace
metadata:
  name: team-platform
  labels:
    # Team
    team: platform
    environment: shared
    
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    
    # labels
    cost-center: platform
    compliance: elevated
    
  annotations:
    description: "Platform team"