# Multi-Tenant ServiceAccounts Configuration

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-frontend-sa
  namespace: team-frontend
  labels:
    team: frontend
    component: identity
  annotations:
    description: "ServiceAccount for frontend team workloads and RBAC"
    kubernetes.io/managed-by: "platform-team"
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-backend-sa
  namespace: team-backend
  labels:
    team: backend
    component: identity
  annotations:
    description: "ServiceAccount for backend team workloads and RBAC"
    kubernetes.io/managed-by: "platform-team"
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-platform-sa
  namespace: team-platform
  labels:
    team: platform
    component: identity
  annotations:
    description: "ServiceAccount for platform team infrastructure operations"
    kubernetes.io/managed-by: "platform-team"
    privilege-level: "cluster-admin"
automountServiceAccountToken: true